### ISSUE TITLE
are worked with 7.1

### ISSUE THREAD

**Issue by djoudi** [bxservice/de.bxservice.metabase#1]
i try to install it in idempiere 7.0 but not worked

**Comment by d-ruiz** [comment]
Hi, the plugin was developed and tested with the latest supported iDempiere version, 8.2. I recommend you to update to the latest version to benefit from all the new features, security updates, and latest plug-ins. 

You can also fork the plugin and modify some sources to make it compatible with your iDempiere version, usually it's just the MANIFEST file that needs to be changed.

Closing the issue.
