### ISSUE TITLE
Unresolved elements 

### ISSUE THREAD

**Issue by djoudi** [bxservice/de.bxservice.metabase#2]
i want to packin this package but i have this issue 

![image](https://user-images.githubusercontent.com/152725/128070754-aeaa3214-151d-4a56-a7b3-95b518df7b31.png)

![image](https://user-images.githubusercontent.com/152725/128070889-c8685507-2075-4c70-8dc9-6f76052b6e43.png)

**Comment by CarlosRuiz-globalqss** [comment]
Hi @djoudi - you don't need to apply packins.

You just need to install the plugin and the packins will be automatically added when the plugin starts.

Anyways, if you want to apply them manually, you must do it in the exact order by version:
2Pack_1.0.0.zip
2Pack_1.0.1.zip
2Pack_1.0.2.zip
2Pack_1.0.3.zip

Regards,

Carlos Ruiz
